//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceRecognition.UI.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FaceRecognition.UI.Resource.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string BROWSE {
            get {
                return ResourceManager.GetString("BROWSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capturing Interval.
        /// </summary>
        public static string CAPTURING_INTERVAL {
            get {
                return ResourceManager.GetString("CAPTURING_INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string CONFIGURATION {
            get {
                return ResourceManager.GetString("CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string CONFIRM {
            get {
                return ResourceManager.GetString("CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GENERAL {
            get {
                return ResourceManager.GetString("GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Video.
        /// </summary>
        public static string INSERT_VIDEO {
            get {
                return ResourceManager.GetString("INSERT_VIDEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known People.
        /// </summary>
        public static string KNOWN_PEOPLE {
            get {
                return ResourceManager.GetString("KNOWN_PEOPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string PREVIEW {
            get {
                return ResourceManager.GetString("PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed.
        /// </summary>
        public static string PROCEED {
            get {
                return ResourceManager.GetString("PROCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string STOP {
            get {
                return ResourceManager.GetString("STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker.
        /// </summary>
        public static string TRACKER {
            get {
                return ResourceManager.GetString("TRACKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow People.
        /// </summary>
        public static string UNKNOWN_PEOPLE {
            get {
                return ResourceManager.GetString("UNKNOWN_PEOPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untracked People.
        /// </summary>
        public static string UNTRACKED_PEOPLE {
            get {
                return ResourceManager.GetString("UNTRACKED_PEOPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Tagging.
        /// </summary>
        public static string VIDEO_TAGGING {
            get {
                return ResourceManager.GetString("VIDEO_TAGGING", resourceCulture);
            }
        }
    }
}
